const root=document.querySelector('#game');
const canvas=document.createElement('canvas');canvas.id='game-canvas';root.replaceChildren(canvas);
const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=true;
let W=innerWidth,H=innerHeight,DPR=1;
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(2,devicePixelRatio||1);canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}
addEventListener('resize',resize);resize();

const WORLD={w:7600,h:2200};
const keys=new Set(),just=new Set();const mouse={x:W/2,y:H/2};
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(!keys.has(k))just.add(k);keys.add(k);if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault()});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
addEventListener('blur',()=>{keys.clear();just.clear()});
addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});

const hero=new Image();hero.src='./assets/hero-sheet.svg';
const enemySheet=new Image();enemySheet.src='./assets/enemy-sheet.svg';
const state={screen:'play',time:0,shake:0,hitstop:0,toast:0,toastTitle:'',toastText:'',zone:'Aether Camp',discovered:new Set(['camp']),saveFlash:0};
const p={x:460,y:1610,w:48,h:86,vx:0,vy:0,face:1,grounded:false,coyote:0,jumpBuffer:0,dash:0,dashCd:0,dashDir:1,inv:0,hp:120,maxHp:120,energy:50,maxEnergy:50,level:1,xp:0,gold:125,combo:0,comboTimer:0,attack:0,attackCd:0,attackPhase:0,anim:0,hurt:0,flask:3};
const platforms=[
{x:-200,y:1810,w:1250,h:500},{x:1050,y:1690,w:720,h:620},{x:1770,y:1490,w:650,h:820},{x:2420,y:1760,w:620,h:550},{x:3040,y:1600,w:840,h:710},{x:3880,y:1400,w:720,h:910},{x:4600,y:1680,w:760,h:630},{x:5360,y:1480,w:820,h:830},{x:6180,y:1260,w:920,h:1050},{x:7040,y:1680,w:620,h:630},
{x:720,y:1390,w:280,h:28},{x:1270,y:1260,w:330,h:28},{x:1880,y:1160,w:300,h:28},{x:2230,y:900,w:270,h:28},{x:2730,y:1320,w:280,h:28},{x:3270,y:1150,w:310,h:28},{x:3700,y:960,w:300,h:28},{x:4220,y:1110,w:290,h:28},{x:4770,y:1230,w:300,h:28},{x:5480,y:990,w:320,h:28},{x:6040,y:850,w:320,h:28}
];
const landmarks=[
{id:'camp',name:'Aether Camp',x:440,y:1640,type:'camp'},
{id:'grove',name:'Whispering Grove',x:1510,y:1190,type:'grove'},
{id:'archive',name:'Sunken Archive',x:2760,y:1240,type:'archive'},
{id:'watch',name:'Old Watchtower',x:3980,y:820,type:'tower'},
{id:'mire',name:'Mire of Bells',x:5220,y:1190,type:'mire'},
{id:'citadel',name:'Crown of Stone',x:6450,y:670,type:'citadel'}];
const quests=[
{id:'light',title:'The First Light',text:'Reach the Old Watchtower',done:false},
{id:'grove',title:'Echoes in the Grove',text:'Discover the lost shrine',done:false},
{id:'warden',title:'The Watcher',text:'Defeat the guardian',done:false}];
const enemies=[];
function spawn(kind,x,y){const boss=kind==='warden';enemies.push({kind,x,y,w:boss?108:68,h:boss?118:82,vx:0,vy:0,hp:boss?900:kind==='stalker'?150:80,max:boss?900:kind==='stalker'?150:80,ground:false,hit:0,attackCd:0,tele:0,active:0,face:-1,phase:1,dead:false,anim:Math.random()*10})}
spawn('mossling',920,1580);spawn('mossling',1490,1320);spawn('stalker',2010,1080);spawn('mossling',2580,1660);spawn('stalker',3300,1500);spawn('mossling',4140,1280);spawn('stalker',4880,1580);spawn('mossling',5580,1380);spawn('warden',6500,1120);
const particles=[],slashes=[],projectiles=[],pickups=[],afterimages=[];
const toastEl=document.querySelector('#toast-stack');
function toast(title,text){state.toastTitle=title;state.toastText=text;state.toast=2800;if(toastEl)toastEl.innerHTML=`<div class="toast"><b>${title}</b><span>${text}</span></div>`}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function overlap(a,b){return a.x-a.w/2<b.x+b.w/2&&a.x+a.w/2>b.x-b.w/2&&a.y-a.h/2<b.y+b.h/2&&a.y+a.h/2>b.y-b.h/2}
function burst(x,y,n=12,c='#d8bf83',power=150){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*power;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,r:1+Math.random()*3,life:260+Math.random()*380,max:640,c})}}
function dust(x,y,n=7){for(let i=0;i<n;i++)particles.push({x:x+(Math.random()-.5)*45,y:y-4,vx:(Math.random()-.5)*70,vy:-20-Math.random()*70,r:2+Math.random()*4,life:300+Math.random()*250,max:550,c:'#9a8c6b'})}
function floatText(x,y,t,c='#e2c77e'){particles.push({text:t,x,y,vx:0,vy:-45,r:0,life:700,max:700,c})}
function xpNeed(){return 120+p.level*90}
function gainXP(n){p.xp+=n;while(p.xp>=xpNeed()){p.xp-=xpNeed();p.level++;p.maxHp+=8;p.hp=p.maxHp;p.maxEnergy+=3;p.energy=p.maxEnergy;toast('Aether awakened',`Level ${p.level} · Vitality increased`)}}
function die(){p.hp=p.maxHp;p.energy=p.maxEnergy;p.x=460;p.y=1610;p.vx=p.vy=0;p.inv=900;p.gold=Math.max(0,p.gold-20);toast('Fallen','The campfire draws you home.')}
function discover(l){if(state.discovered.has(l.id))return;state.discovered.add(l.id);state.zone=l.name;toast(l.name,'Landmark discovered');if(l.id==='grove')quests[1].done=true;if(l.id==='watch')quests[0].done=true;state.saveFlash=1200;save()}
function save(){localStorage.setItem('aether-save',JSON.stringify({x:p.x,y:p.y,level:p.level,xp:p.xp,gold:p.gold,hp:p.hp,energy:p.energy,discovered:[...state.discovered],quests:quests.map(q=>q.done)}))}
function load(){try{const s=JSON.parse(localStorage.getItem('aether-save'));if(!s)return;p.x=s.x??p.x;p.y=s.y??p.y;p.level=s.level??1;p.xp=s.xp??0;p.gold=s.gold??125;p.hp=s.hp??p.hp;p.energy=s.energy??p.energy;(s.discovered||[]).forEach(x=>state.discovered.add(x));(s.quests||[]).forEach((v,i)=>{if(quests[i])quests[i].done=!!v})}catch{}}
load();

function move(dt){
 const left=keys.has('a')||keys.has('arrowleft'),right=keys.has('d')||keys.has('arrowright');let axis=(right?1:0)-(left?1:0);if(axis)p.face=axis;
 if(just.has(' '))p.jumpBuffer=130;else p.jumpBuffer=Math.max(0,p.jumpBuffer-dt);
 p.coyote=p.grounded?110:Math.max(0,p.coyote-dt);
 if(just.has('shift')&&p.dashCd<=0&&!p.dash&&!p.attack&&p.energy>=12){p.dash=125;p.dashCd=360;p.inv=170;p.energy-=12;p.dashDir=axis||p.face;burst(p.x,p.y,12,'#c9b47d',190);for(let i=0;i<4;i++)afterimages.push({x:p.x,y:p.y,face:p.face,life:180,max:180})}
 if(p.dash>0){p.dash=Math.max(0,p.dash-dt);p.vx=p.dashDir*900;p.vy=0;if(Math.random()<.45)afterimages.push({x:p.x,y:p.y,face:p.face,life:150,max:150})}
 else{
   const sprint=keys.has('shift')&&axis&&p.energy>0;const speed=sprint?390:315;p.vx=axis*speed;
   if(sprint)p.energy=Math.max(0,p.energy-22*dt/1000);else p.energy=Math.min(p.maxEnergy,p.energy+18*dt/1000);
   if(just.has(' ')&&p.coyote>0){p.vy=-735;p.grounded=false;p.coyote=0;p.jumpBuffer=0;dust(p.x,p.y+p.h/2,9)}
   if(!keys.has(' ')&&p.vy<-230)p.vy=-230;
 }
 p.anim+=dt*(Math.abs(p.vx)/180);p.inv=Math.max(0,p.inv-dt);p.dashCd=Math.max(0,p.dashCd-dt);p.hurt=Math.max(0,p.hurt-dt);resolvePlayer(dt);
}
function resolvePlayer(dt){const oldY=p.y;p.vy+=1950*dt/1000;p.x+=p.vx*dt/1000;p.y+=p.vy*dt/1000;p.grounded=false;for(const r of platforms){if(p.x+p.w/2<r.x||p.x-p.w/2>r.x+r.w||p.y+p.h/2<r.y-4||p.y-p.h/2>r.y+r.h)continue;if(oldY+p.h/2<=r.y&&p.y+p.h/2>=r.y&&p.vy>=0){p.y=r.y-p.h/2;p.vy=0;p.grounded=true}else if(oldY-p.h/2>=r.y+r.h&&p.y-p.h/2<=r.y+r.h&&p.vy<0){p.y=r.y+r.h+p.h/2;p.vy=0}else if(p.x+p.w/2>r.x&&p.x-p.w/2<r.x+r.w){if(p.x<r.x)p.x=r.x-p.w/2;else p.x=r.x+r.w+p.w/2;p.vx=0}}p.x=clamp(p.x,30,WORLD.w-30);if(p.y>WORLD.h+200)die()}
function attack(){if(state.screen!=='play'||p.attackCd>0||p.dash)return;p.attack=230;p.attackCd=285;p.combo=p.comboTimer>0?(p.combo%3)+1:1;p.comboTimer=760;p.attackPhase=0;slashes.push({x:p.x+p.face*55,y:p.y-8,face:p.face,t:0,life:230,combo:p.combo});burst(p.x+p.face*42,p.y-15,5,'#d6bc7c',90)}
function cast(i){if(state.screen!=='play')return;if(i===0&&p.energy>=10){p.energy-=10;projectiles.push({x:p.x+p.face*42,y:p.y-18,vx:p.face*850,vy:-40,life:850});burst(p.x+p.face*25,p.y-15,8,'#a5c09a',130)}if(i===1&&p.energy>=16){p.energy-=16;for(const e of enemies)if(!e.dead&&Math.hypot(e.x-p.x,(e.y-p.y)*.7)<220){e.hp-=65;e.hit=180;e.vx=Math.sign(e.x-p.x||p.face)*420;e.vy=-300;floatText(e.x,e.y-55,'-65','#d8bf83');burst(e.x,e.y,16,'#a5c09a',190);if(e.hp<=0)kill(e)}burst(p.x,p.y,24,'#9eb89b',260)}if(i===2&&p.flask>0){p.flask--;p.hp=Math.min(p.maxHp,p.hp+42);p.inv=500;floatText(p.x,p.y-65,'+42','#d8bf83');burst(p.x,p.y,18,'#d8bf83',210)}}
function hitEnemies(){if(p.attack<100||p.attack>175)return;const reach=115+p.combo*8;for(const e of enemies){if(e.dead||e.hit>0)continue;const dx=e.x-p.x,dy=e.y-p.y;if(Math.abs(dx)<reach&&Math.abs(dy)<95&&Math.sign(dx||p.face)===p.face){const dmg=22+p.combo*9;e.hp-=dmg;e.hit=180;e.vx=p.face*(280+p.combo*50);e.vy=-250;state.hitstop=45;state.shake=8;floatText(e.x,e.y-60,'-'+dmg);burst(e.x,e.y,13,e.kind==='warden'?'#d2a25e':'#b7785f',170);if(e.hp<=0)kill(e)}}}
function kill(e){if(e.dead)return;e.dead=true;gainXP(e.kind==='warden'?500:e.kind==='stalker'?85:42);p.gold+=e.kind==='warden'?120:10;pickups.push({x:e.x,y:e.y,t:e.kind==='warden'?'WARDEN SIGIL':'AETHER SHARD',life:8000});burst(e.x,e.y,32,e.kind==='warden'?'#d8b66e':'#9cad86',250);if(e.kind==='warden'){quests[2].done=true;toast('The Watcher falls','Aether Camp has a new relic.');save()}}
function updateAttack(dt){if(p.attack<=0)return;const prev=p.attack;p.attack=Math.max(0,p.attack-dt);if(prev>120&&p.attack<=120)hitEnemies()}
function updateEnemies(dt){for(const e of enemies){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);e.attackCd=Math.max(0,e.attackCd-dt);e.tele=Math.max(0,e.tele-dt);e.active=Math.max(0,e.active-dt);e.anim+=dt*.006;const dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy);if(dist>1000)continue;e.face=dx<0?-1:1;if(e.kind==='warden'&&e.hp<e.max*.5)e.phase=2;if(e.active>0){e.vx*=.82;if(e.active<90&&!p.inv&&Math.abs(dx)<(e.kind==='warden'?120:80)&&Math.abs(dy)<100){const dmg=e.kind==='warden'?(e.phase===2?24:18):9;p.hp-=dmg;p.hurt=250;p.inv=450;p.vx=Math.sign(dx)*380;p.vy=-280;state.shake=10;floatText(p.x,p.y-65,'-'+dmg,'#c56f5c');if(p.hp<=0)die()}}else if(e.tele>0){e.vx*=.86}else if(e.attackCd<=0&&dist<150+(e.kind==='warden'?40:0)&&Math.abs(dy)<120){e.tele=e.kind==='warden'?(e.phase===2?360:430):330;e.active=e.kind==='warden'?(e.phase===2?180:150):120;e.attackCd=e.kind==='warden'?900:720;burst(e.x,e.y-30,4,'#c7a967',80)}else if(dist<560){const speed=e.kind==='warden'?(e.phase===2?260:190):e.kind==='stalker'?190:145;e.vx=clamp(e.vx+Math.sign(dx)*speed*dt/1000,-speed,speed);if(e.kind==='stalker'&&e.ground&&Math.abs(dy)>100&&Math.random()<.02)e.vy=-600}else e.vx*=.96;e.x+=e.vx*dt/1000;e.vy+=1750*dt/1000;e.y+=e.vy*dt/1000;e.ground=false;for(const r of platforms){if(e.x+e.w/2<r.x||e.x-e.w/2>r.x+r.w)continue;if(e.y+e.h/2>=r.y&&e.y+e.h/2<=r.y+35&&e.vy>=0){e.y=r.y-e.h/2;e.vy=0;e.ground=true}}}}
function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const a=projectiles[i];a.x+=a.vx*dt/1000;a.y+=a.vy*dt/1000;a.vy+=300*dt/1000;a.life-=dt;let hit=false;for(const e of enemies)if(!e.dead&&Math.hypot(e.x-a.x,e.y-a.y)<70){e.hp-=48;e.hit=150;e.vx=Math.sign(a.vx)*300;e.vy=-170;floatText(e.x,e.y-55,'-48','#a5c09a');burst(e.x,e.y,10,'#9eb89b',150);hit=true;if(e.hp<=0)kill(e);break}if(hit||a.life<=0)projectiles.splice(i,1)}}
function updateFx(dt){for(let i=particles.length-1;i>=0;i--){const q=particles[i];q.life-=dt;q.x+=q.vx*dt/1000;q.y+=q.vy*dt/1000;q.vy+=q.text?0:250*dt/1000;if(q.life<=0)particles.splice(i,1)}for(let i=slashes.length-1;i>=0;i--){slashes[i].t+=dt;if(slashes[i].t>slashes[i].life)slashes.splice(i,1)}for(let i=afterimages.length-1;i>=0;i--){afterimages[i].life-=dt;if(afterimages[i].life<=0)afterimages.splice(i,1)}for(let i=pickups.length-1;i>=0;i--){pickups[i].life-=dt;if(Math.hypot(p.x-pickups[i].x,p.y-pickups[i].y)<80){floatText(p.x,p.y-65,'+'+pickups[i].t,'#d8bf83');pickups.splice(i,1);p.gold+=3}else if(pickups[i].life<=0)pickups.splice(i,1)}}
function update(dt){if(state.screen!=='play')return;if(state.hitstop){state.hitstop=Math.max(0,state.hitstop-dt);return}state.time+=dt;state.toast=Math.max(0,state.toast-dt);state.shake=Math.max(0,state.shake-dt);p.comboTimer=Math.max(0,p.comboTimer-dt);p.attackCd=Math.max(0,p.attackCd-dt);updateAttack(dt);move(dt);updateEnemies(dt);updateProjectiles(dt);updateFx(dt);for(const l of landmarks)if(Math.abs(p.x-l.x)<150&&Math.abs(p.y-l.y)<220)discover(l);if(p.x>WORLD.w-120){toast('Beyond the frontier','This chapter ends here.');p.x=WORLD.w-140}state.saveFlash=Math.max(0,state.saveFlash-dt)}
function camera(){return {x:clamp(p.x-W*.38,0,WORLD.w-W),y:clamp(p.y-H*.58,0,WORLD.h-H)}}
function sky(cam){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#17241f');g.addColorStop(.5,'#314437');g.addColorStop(1,'#6f7259');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const sunX=W*.72-cam.x*.05;const sg=ctx.createRadialGradient(sunX,H*.28,10,sunX,H*.28,300);sg.addColorStop(0,'rgba(242,211,145,.32)');sg.addColorStop(1,'rgba(242,211,145,0)');ctx.fillStyle=sg;ctx.fillRect(0,0,W,H);for(let layer=0;layer<3;layer++){const par=[.08,.16,.27][layer];ctx.fillStyle=['#26372f','#314538','#40523e'][layer];ctx.beginPath();ctx.moveTo(0,H);for(let x=-100;x<W+120;x+=90){const wx=x+cam.x*par,y=H*(.28+.12*layer)+Math.sin(wx*.0018)*55+Math.sin(wx*.0041)*24;ctx.lineTo(x,y)}ctx.lineTo(W,H);ctx.fill()}}
function tree(x,y,s,par,cam){const sx=x-cam.x*par,sy=y-cam.y*.04;if(sx<-180||sx>W+180)return;ctx.save();ctx.translate(sx,sy);ctx.scale(s,s);ctx.fillStyle='#2b241d';ctx.fillRect(-10,-180,20,180);ctx.beginPath();ctx.moveTo(0,-150);ctx.lineTo(-80,-230);ctx.lineTo(-45,-225);ctx.lineTo(-105,-295);ctx.lineTo(-45,-275);ctx.lineTo(-8,-345);ctx.lineTo(28,-275);ctx.lineTo(90,-300);ctx.lineTo(48,-230);ctx.lineTo(90,-238);ctx.closePath();ctx.fillStyle='#253b2e';ctx.fill();ctx.beginPath();ctx.moveTo(0,-170);ctx.lineTo(-58,-240);ctx.lineTo(-20,-232);ctx.lineTo(-70,-285);ctx.lineTo(0,-250);ctx.lineTo(55,-290);ctx.lineTo(30,-225);ctx.lineTo(75,-235);ctx.closePath();ctx.fillStyle='#3f5940';ctx.fill();ctx.restore()}
function backgroundArt(cam){for(let i=-1;i<22;i++)tree(i*410+100,1560,1.1+(i%3)*.18,.16,cam);for(let i=-1;i<18;i++)tree(i*500+230,1680,.75+(i%2)*.18,.28,cam);const tower=3980-cam.x*.34;ctx.fillStyle='#27302a';ctx.fillRect(tower-70,390,140,470);ctx.fillRect(tower-95,370,190,32);ctx.fillStyle='#485047';ctx.fillRect(tower-55,450,110,390);for(let y=470;y<800;y+=75){ctx.fillStyle='#171d19';ctx.fillRect(tower-18,y,36,45)}}
function drawPlatform(r,cam){const x=r.x-cam.x,y=r.y-cam.y;if(x>W+100||x+r.w<-100)return;ctx.fillStyle='#272a22';ctx.fillRect(x,y,r.w,r.h);const top=ctx.createLinearGradient(x,y,x,y+26);top.addColorStop(0,'#81906b');top.addColorStop(.35,'#59664d');top.addColorStop(1,'#3e4031');ctx.fillStyle=top;ctx.fillRect(x,y,r.w,20);ctx.fillStyle='#765f43';ctx.fillRect(x,y+18,r.w,12);for(let i=18;i<r.w;i+=52){ctx.fillStyle='#34392c';ctx.fillRect(x+i,y+30,5,Math.min(r.h-30,80));ctx.fillStyle='#5b4938';ctx.fillRect(x+i+5,y+38,18,5)}}
function landmarkArt(l,cam){const x=l.x-cam.x,y=l.y-cam.y;if(x<-300||x>W+300)return;ctx.save();ctx.translate(x,y);if(l.type==='camp'){ctx.fillStyle='#4b382b';ctx.beginPath();ctx.moveTo(-120,25);ctx.lineTo(0,-95);ctx.lineTo(120,25);ctx.closePath();ctx.fill();ctx.fillStyle='#72523a';ctx.fillRect(-90,18,180,12);ctx.fillStyle='#c58d50';ctx.beginPath();ctx.arc(0,2,27,0,Math.PI*2);ctx.fill();for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.strokeStyle='rgba(232,192,113,.55)';ctx.beginPath();ctx.moveTo(Math.cos(a)*25,Math.sin(a)*25);ctx.lineTo(Math.cos(a)*48,Math.sin(a)*48);ctx.stroke()}}else if(l.type==='tower'||l.type==='citadel'){ctx.fillStyle='#57564c';ctx.fillRect(-70,-260,140,280);ctx.fillStyle='#777563';ctx.fillRect(-90,-280,180,22);ctx.fillStyle='#262923';for(let yy=-220;yy<0;yy+=65)ctx.fillRect(-18,yy,36,42);ctx.fillStyle='#8d815e';ctx.fillRect(-110,-288,220,8)}else if(l.type==='grove'){for(let i=0;i<7;i++){ctx.fillStyle=i%2?'#314b37':'#405a3e';ctx.beginPath();ctx.arc(-90+i*30,-30-(i%3)*35,45+(i%2)*12,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#8e7c55';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,65,Math.PI,Math.PI*2);ctx.stroke()}else if(l.type==='archive'){ctx.fillStyle='#4e4b40';ctx.fillRect(-110,-90,220,90);ctx.fillStyle='#7a765f';for(let i=-90;i<=90;i+=45)ctx.fillRect(i,-75,28,50);ctx.fillStyle='#242a24';ctx.fillRect(-120,-105,240,15)}else{ctx.strokeStyle='#695b49';ctx.lineWidth=9;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(-100+i*50,0);ctx.lineTo(-70+i*50,-70-(i%2)*25);ctx.stroke()}}ctx.restore();ctx.fillStyle='#e0ceaa';ctx.font='600 13px Georgia';ctx.textAlign='center';ctx.shadowColor='#111';ctx.shadowBlur=8;ctx.fillText(l.name,x,y-300);ctx.shadowBlur=0}
function drawSprite(img,frame,x,y,face,w,h){ctx.save();ctx.translate(x,y);ctx.scale(face,1);ctx.drawImage(img,frame*128,0,128,128,-w/2,-h*.82,w,h);ctx.restore()}
function drawEnemySprite(frame,x,y,face,kind,w,h){ctx.save();ctx.translate(x,y);ctx.scale(face,1);ctx.drawImage(enemySheet,(kind==='warden'?frame%4:frame)*128,0,128,128,-w/2,-h*.84,w,h);ctx.restore()}
function drawHero(cam){for(const a of afterimages){ctx.globalAlpha=(a.life/a.max)*.25;drawSprite(hero,Math.floor(p.anim)%6,a.x-cam.x,a.y-cam.y,a.face,92,116);ctx.globalAlpha=1}if(hero.complete)drawSprite(hero,Math.floor(p.anim)%6,p.x-cam.x,p.y-cam.y,p.face,92,116);else{ctx.fillStyle='#304c38';ctx.beginPath();ctx.ellipse(p.x-cam.x,p.y-cam.y-20,27,42,0,0,Math.PI*2);ctx.fill()}}
function drawEnemy(e,cam){if(e.hit>0&&Math.floor(e.hit/35)%2===0)ctx.globalAlpha=.45;const x=e.x-cam.x,y=e.y-cam.y;if(enemySheet.complete)drawEnemySprite(Math.floor(e.anim)%4,x,y,e.face,e.kind,e.w,e.h);else{ctx.fillStyle=e.kind==='warden'?'#68583e':'#49623f';ctx.beginPath();ctx.ellipse(x,y,e.w/2,e.h/2,0,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(e.tele>0){ctx.strokeStyle=`rgba(224,190,108,${.35+.35*Math.sin(state.time*.025)})`;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y-55,e.w*.72,Math.PI,Math.PI*2);ctx.stroke()}}
function drawWorld(cam){sky(cam);backgroundArt(cam);for(const r of platforms)drawPlatform(r,cam);for(const l of landmarks)landmarkArt(l,cam);for(const a of projectiles){const x=a.x-cam.x,y=a.y-cam.y;ctx.strokeStyle='#a8c29a';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x-a.vx*.025,y+5);ctx.lineTo(x,y);ctx.stroke();ctx.fillStyle='#d9d3a0';ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fill()}for(const e of enemies)if(!e.dead)drawEnemy(e,cam);drawHero(cam);for(const s of slashes){const x=s.x-cam.x,y=s.y-cam.y,pr=s.t/s.life;ctx.save();ctx.translate(x,y);ctx.scale(s.face,1);ctx.strokeStyle=`rgba(235,215,167,${1-pr})`;ctx.lineWidth=5+s.combo;ctx.beginPath();ctx.arc(0,0,72+s.combo*10,-1.05,.65);ctx.stroke();ctx.restore()}for(const q of particles){const x=q.x-cam.x,y=q.y-cam.y;if(q.text){ctx.globalAlpha=q.life/q.max;ctx.fillStyle=q.c;ctx.font='bold 15px Georgia';ctx.textAlign='center';ctx.fillText(q.text,x,y)}else{ctx.globalAlpha=q.life/q.max;ctx.fillStyle=q.c;ctx.beginPath();ctx.arc(x,y,q.r,0,Math.PI*2);ctx.fill()}}ctx.globalAlpha=1;ctx.fillStyle='rgba(20,30,22,.72)';for(let i=0;i<14;i++){const x=i*170-(cam.x*.55%170);ctx.beginPath();ctx.ellipse(x,H-5,80,26,0,0,Math.PI*2);ctx.fill()}}
function panel(title,sub){ctx.fillStyle='rgba(12,16,13,.94)';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#806b4d';ctx.lineWidth=1;ctx.strokeRect(70,55,W-140,H-110);ctx.fillStyle='#e4d5b7';ctx.font='bold 34px Georgia';ctx.textAlign='left';ctx.fillText(title,105,115);ctx.fillStyle='#9d987f';ctx.font='13px Inter';ctx.fillText(sub,107,140)}
function drawMap(){panel('Frontier Map','M to return · discovered landmarks are marked in gold');const x0=130,y0=210,w=W-260,h=H-330;ctx.fillStyle='#273a30';ctx.fillRect(x0,y0,w,h);ctx.strokeStyle='#5b694e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x0+20,y0+h*.72);ctx.bezierCurveTo(x0+w*.2,y0+h*.45,x0+w*.45,y0+h*.8,x0+w*.62,y0+h*.35);ctx.bezierCurveTo(x0+w*.75,y0+h*.1,x0+w*.88,y0+h*.5,x0+w-20,y0+h*.2);ctx.stroke();for(const l of landmarks){const x=x0+(l.x/WORLD.w)*w,y=y0+(l.y/2000)*h;ctx.fillStyle=state.discovered.has(l.id)?'#d3b66f':'#69705f';ctx.beginPath();ctx.arc(x,y,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ddd1b1';ctx.font='12px Georgia';ctx.fillText(l.name,x+15,y+4)}}
function drawQuest(){panel('Quest Journal','J or Esc to return');let y=205;for(const q of quests){ctx.fillStyle=q.done?'#8e9a76':'#d7c18d';ctx.font='bold 20px Georgia';ctx.fillText((q.done?'✓ ':'')+q.title,120,y);ctx.fillStyle='#a9a28e';ctx.font='13px Inter';ctx.fillText(q.text,145,y+25);y+=78}}
function drawCharacter(){panel('Veyra · Wayfarer','C to return');ctx.fillStyle='#e0d1b1';ctx.font='18px Georgia';ctx.fillText(`Level ${p.level}`,130,205);ctx.fillText(`Health ${p.hp} / ${p.maxHp}`,130,240);ctx.fillText(`Aether ${Math.floor(p.energy)} / ${p.maxEnergy}`,130,275);ctx.fillText(`Gold ${p.gold}`,130,310);ctx.fillStyle='#98937e';ctx.font='13px Inter';ctx.fillText('Built for speed: instant turns, variable jump, directional dash, buffered attacks.',130,355);ctx.fillText('Abilities: Q Aether Bolt · E Verdant Burst · R Flask',130,380)}
function drawAbilities(){panel('Abilities','K to return');const a=[['Q','Aether Bolt','Fast ranged burst'],['E','Verdant Burst','Close-range area strike'],['R','Second Wind','Restore health']];let y=220;for(const z of a){ctx.fillStyle='#d5bd83';ctx.font='bold 24px Georgia';ctx.fillText(z[0],135,y);ctx.fillStyle='#e0d4ba';ctx.font='bold 17px Georgia';ctx.fillText(z[1],190,y);ctx.fillStyle='#9b9684';ctx.font='12px Inter';ctx.fillText(z[2],190,y+22);y+=85}}
function hud(){const hf=document.querySelector('#health-fill'),ef=document.querySelector('#energy-label'),hl=document.querySelector('#health-label'),xl=document.querySelector('#xp-label'),ll=document.querySelector('#level-label'),gf=document.querySelector('#gold-label');if(hf)hf.style.width=(p.hp/p.maxHp*100)+'%';if(hl)hl.textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;if(ef)ef.textContent=`${Math.floor(p.energy)} / ${p.maxEnergy}`;if(xl)xl.textContent=`${p.xp} / ${xpNeed()} XP`;if(ll)ll.textContent='LV '+p.level;if(gf)gf.textContent=p.gold;const objective=document.querySelector('.objective strong');if(objective){const q=quests.find(q=>!q.done);objective.textContent=q?q.title:'Frontier uncovered';const s=document.querySelector('.objective span');if(s)s.textContent=q?q.text:'Explore, fight, and return to camp.'}const z=document.querySelector('.zone-title');if(z)z.textContent=state.zone;const zs=document.querySelector('.zone-subtitle');if(zs)zs.textContent=`${state.discovered.size} discoveries · ${quests.filter(q=>q.done).length}/${quests.length} quests`}
function draw(){const cam=camera();ctx.save();if(state.shake){const s=state.shake*.35;ctx.translate((Math.random()-.5)*s,(Math.random()-.5)*s)}if(state.screen==='play')drawWorld(cam);else if(state.screen==='map')drawMap();else if(state.screen==='quests')drawQuest();else if(state.screen==='character')drawCharacter();else drawAbilities();ctx.restore();hud();just.clear()}
addEventListener('mousedown',e=>{if(e.button===0)attack()});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(!just.has(k))return;if(k==='q')cast(0);if(k==='e')cast(1);if(k==='r')cast(2);if(k==='m')state.screen=state.screen==='map'?'play':'map';if(k==='j')state.screen=state.screen==='quests'?'play':'quests';if(k==='c')state.screen=state.screen==='character'?'play':'character';if(k==='k')state.screen=state.screen==='abilities'?'play':'abilities';if(k==='escape')state.screen='play';});

toast('Aether Camp','A/D move · Space jump · Shift dash · LMB combo · Q/E/R abilities · M map');
let last=performance.now();function loop(now){const dt=Math.min(32,now-last);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
